In [ ]:
import pandas as pd

In [2]:
data = {
"Employee": ["Amit", "Priya", "Rahul", "Sneha", "Ravi",
"Anita"],
"Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
"City": ["Bangalore", "Chennai", "Bangalore", "Delhi",
"Chennai", "Mumbai"],
"Salary": [60000, 50000, 65000, 70000, 52000, 58000],
"Experience": [5, 3, 7, 10, 4, 6]
}

In [3]:
df=pd.DataFrame(data)
df

  Employee Department       City  Salary  Experience
0     Amit         IT  Bangalore   60000           5
1    Priya         HR    Chennai   50000           3
2    Rahul         IT  Bangalore   65000           7
3    Sneha    Finance      Delhi   70000          10
4     Ravi         HR    Chennai   52000           4
5    Anita         IT     Mumbai   58000           6

In [5]:
df.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         51000.0
IT         61000.0
Name: Salary, dtype: float64

In [6]:
df.groupby("Department")["Salary"].sum()

Department
Finance     70000
HR         102000
IT         183000
Name: Salary, dtype: int64

In [7]:
df.groupby("Department")["Experience"].max()

Department
Finance    10
HR          4
IT          7
Name: Experience, dtype: int64

In [8]:
df.groupby("Department")["Salary"].agg(["mean","sum","min","max"])

               mean     sum    min    max
Department
Finance     70000.0   70000  70000  70000
HR          51000.0  102000  50000  52000
IT          61000.0  183000  58000  65000

In [10]:
df.groupby("Department").agg({
    "Salary":["mean","sum"],
    "Experience":["mean","max"]
})

             Salary         Experience
               mean     sum       mean max
Department
Finance     70000.0   70000       10.0  10
HR          51000.0  102000        3.5   4
IT          61000.0  183000        6.0   7

In [15]:
df.groupby("Department").agg(
    Avg_Salary=("Salary","mean"),
    Total_Salary=("Salary","sum"),
    Max_Experience=("Experience","max")
)

            Avg_Salary  Total_Salary  Max_Experience
Department
Finance        70000.0         70000              10
HR             51000.0        102000               4
IT             61000.0        183000               7

In [16]:
employees = pd.DataFrame({
"EmpID": [1, 2, 3, 4],
"Name": ["Amit", "Priya", "Rahul", "Sneha"],
"DeptID": [101, 102, 101, 103],
"Salary": [60000, 50000, 65000, 70000]
})
departments = pd.DataFrame({
"DeptID": [101, 102, 104],
"Department": ["IT", "HR", "Finance"]
})
employees,departments

(   EmpID   Name  DeptID  Salary
 0      1   Amit     101   60000
 1      2  Priya     102   50000
 2      3  Rahul     101   65000
 3      4  Sneha     103   70000,
    DeptID Department
 0     101         IT
 1     102         HR
 2     104    Finance)

In [17]:
pd.merge(employees,departments,on="DeptID",how="inner")

   EmpID   Name  DeptID  Salary Department
0      1   Amit     101   60000         IT
1      2  Priya     102   50000         HR
2      3  Rahul     101   65000         IT

In [18]:
pd.merge(employees,departments,on="DeptID",how="left")

   EmpID   Name  DeptID  Salary Department
0      1   Amit     101   60000         IT
1      2  Priya     102   50000         HR
2      3  Rahul     101   65000         IT
3      4  Sneha     103   70000        NaN

In [19]:
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID   Salary Department
0    1.0   Amit     101  60000.0         IT
1    3.0  Rahul     101  65000.0         IT
2    2.0  Priya     102  50000.0         HR
3    NaN    NaN     104      NaN    Finance

In [20]:
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID   Name  DeptID   Salary Department
0    1.0   Amit     101  60000.0         IT
1    3.0  Rahul     101  65000.0         IT
2    2.0  Priya     102  50000.0         HR
3    4.0  Sneha     103  70000.0        NaN
4    NaN    NaN     104      NaN    Finance

In [21]:
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID  Salary Department
0      1   Amit     101   60000         IT
1      2  Priya     102   50000         HR
2      3  Rahul     101   65000         IT

In [22]:
employees.set_index("DeptID",inplace=True)

In [23]:
departments.set_index("DeptID",inplace=True)
employees.join(departments)

        EmpID   Name  Salary Department
DeptID
101         1   Amit   60000         IT
102         2  Priya   50000         HR
101         3  Rahul   65000         IT
103         4  Sneha   70000        NaN

In [25]:
df1=employees.iloc[:2]
df2=employees.iloc[2:]
pd.concat([df1,df2])

        EmpID   Name  Salary
DeptID
101         1   Amit   60000
102         2  Priya   50000
101         3  Rahul   65000
103         4  Sneha   70000

In [26]:
extra=pd.DataFrame({"bonus":[5000,6000,5500,7000]})
pd.concat([employees.reset_index(drop=True),extra])

   EmpID   Name   Salary   bonus
0    1.0   Amit  60000.0     NaN
1    2.0  Priya  50000.0     NaN
2    3.0  Rahul  65000.0     NaN
3    4.0  Sneha  70000.0     NaN
0    NaN    NaN      NaN  5000.0
1    NaN    NaN      NaN  6000.0
2    NaN    NaN      NaN  5500.0
3    NaN    NaN      NaN  7000.0

In [28]:
pd.concat([df1,df2])

        EmpID   Name  Salary
DeptID
101         1   Amit   60000
102         2  Priya   50000
101         3  Rahul   65000
103         4  Sneha   70000